python trainer.py \
--dataset CRN \
--class_choice multiclass \
--inversion_mode multiclass \
--conditional_gan True \
--visualize \
--mask_type k_mask \
--save_inversion_path ./saved_results/CRN_multiclass/ \
--ckpt_load ./multiclass_pretrained_models_cgan/cgan_multiclass_chair_table_500_epochs.pt \
--dataset_path ./input_shapes/shapenet_crn_dataset/ \
--class_range chair